### ISSUE TITLE
Fix remote: Permission to Sage-Bionetworks/nlp-sandbox-schemas.git denied to github-actions[bot].

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-schemas#42]
When trying to fix #32 , I may have introduce a bug that lead to the following error to be generated in a PR:

```
Run ad-m/github-push-action@master
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch gh-pages
remote: Permission to Sage-Bionetworks/nlp-sandbox-schemas.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/Sage-Bionetworks/nlp-sandbox-schemas.git/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by tschaffter** [comment]
Here are the logs for the same step but from a PR before I made changes that may have introduced this bug:

```
Run ad-m/github-push-action@master
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch gh-pages
To https://github.com/Sage-Bionetworks/nlp-sandbox-schemas.git
   9166740..c1e11c2  HEAD -> gh-pages
```

**Comment by tschaffter** [comment]
Is it because it's a PR from someone with only Read access to this repo?

**Comment by tschaffter** [comment]
I re-run the workflow triggered by @gkowalski PR but the same error arose.

**Comment by tschaffter** [comment]
This PR that I created successfully run the CI workflow:
https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/pull/43

So the issue is likely due to who makes a commit that trigger the workflow. I considered that this issue may arise as I was concerned by content created by random people being pushed to GitHub pages when the workflow run in PRs. For now I'll disable the doc being published during PR.

**Comment by tschaffter** [comment]
@gkowalski PR passes all checks now that I have disabled pushing the docs in PRs.
https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/pull/41
